;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[Variables]
;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

;;HOW TO CHANGE VALUES IN TEXT EDITOR
;;make sure when you change any app / game variable there is an image with the same name in the @Resources folder.
;;names of the image will be the name displayed in the skin. Make sure you change the name of the image to what you want to be shown.
;;please keep the ""s.

;=============ROW 1===============
AppCount1=7
;Update this value everytime you inserted a new value below.

app0=Firefox
applink0="C:\Program Files\Mozilla Firefox\firefox.exe"

app1=Spotify
applink1="C:\Users\Jax4Real\AppData\Roaming\Spotify\spotify.exe"

app2=Discord
applink2="C:\Users\Jax4Real\AppData\Local\Discord\app-0.0.307\discord.exe"

app3=Screen Snip
applink3="%windir%\system32\SnippingTool.exe"

app4=Paint.net
applink4="C:\Program Files\paint.net\PaintDotNet.exe"

app5=Sublime Text
applink5="C:\Program Files\Sublime Text 3\sublime_text.exe"

app6=Steam
applink6="C:\Program Files (x86)\Steam\Steam.exe"

app7=Epic Games
applink7="D:\Epic Games\Launcher\Portal\Binaries\Win32\EpicGamesLauncher.exe"

;=============ROW 2===============
AppCount2=7
;Update this value everytime you inserted a new value below.

app8=Explorer
applink8="C:\Windows\explorer.exe"

app9=Whiteboard
applink9="shell:appsfolder\Microsoft.Whiteboard_8wekyb3d8bbwe!Whiteboard"

app10=Word
applink10="C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE"

app11=Excel
applink11="C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE"

app12=Powerpoint
applink12="C:\Program Files (x86)\Microsoft Office\root\Office16\POWERPNT.EXE"

app13=Photoshop
applink13="C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe"

app14=After Effects
applink14="C:\Program Files\Adobe\Adobe After Effects 2020\Support Files\AfterFX.exe"

app15=Illustrator
applink15=""

;=============ROW 3===============
AppCount3=2
;Update this value everytime you inserted a new value below.

app16=Calculator
applink16="C:\Windows\System32\Calc.exe"

app17=Wallpaper Engine
applink17="D:\SteamLibrary\steamapps\common\wallpaper_engine\wallpaper32.exe"

app18=Groove
applink18="D:\SteamLibrary\steamapps\common\wallpaper_engine\wallpaper32.exe"
;————————————————————————————————————————————————————————————————————————

GameMaxIndex=7
;Update this value everytime you inserted a new value below.

game0=RocketLeagueGame
gamelink0="com.epicgames.launcher://apps/Sugar?action=launch&silent=true"

game1=FortniteGame
gamelink1="C:\Users\Jax4Real\Desktop\Fortnite.url"

game2=AmongusGame
gamelink2="C:\Program Files\Among Us\Among Us\Among Us.exe"

game3=MinecraftGame
gamelink3="C:\Program Files (x86)\Minecraft Launcher\MinecraftLauncher.exe"

game4=OsuGame
gamelink4="C:\Users\Jax4Real\AppData\Local\osu!\osu!.exe"

game5=BLCGame
gamelink5="D:\Minecraft\Badlion Client\Badlion Client.exe"

game6=ApexGame
gamelink6="steam://rungameid/1172470"

game7=RobloxGame
gamelink7="https://www.reddit.com"

game8=
gamelink8=""

;————————————————————————————————————————————————————————————————————————
;=============ROW 1===============
WebCount1=7

web0=Reddit
weblink0="https://www.reddit.com"

web1=Calendar
weblink1="https://calendar.google.com/calendar/u/0/r"

web2=Translate
weblink2="https://translate.google.com#view=home&op=translate&sl=en&tl=zh-TW&text=Type%20here%20to%20start%20translation"

web3=Youtube
weblink3="https://www.youtube.com"

web4=Classroom
weblink4="https://classroom.google.com/u/1/a/not-turned-in/all"

web5=Whatsapp
weblink5="https://web.whatsapp.com/"

web6=Drive
weblink6="https://drive.google.com"

web7=Icon8
weblink7="https://icons8.com/"

;=============ROW 2===============
WebCount2=0

web8=#@#Images\.png
weblink8=""
webname8="..."

web9=#@#Images\.png
weblink9=""
webname9="..."

;————————————————————————————————————————————————————————————————————————CUSTOMIZABLE VALUES

Page=0
;Initialized page
SideRotation=-20
;Initialized rotation angle for side pieces
MiddleRotation=20
;Initialized rotation angle for middle piece
AnimationSpeed=250
;The time to complete one animation action
PowerButtonSize=50
;Sizes for the buttons in the power menu
IconMod=10
;When hovering on the top page buttons, how much would their size change
AppGap=10
;The gap between different app icons
AppMod=10
;When hovering on the app icons, how much would their size change
AppHeight=225
;The y value of application icons
AppSize=37
;Height and Width of app icons
SettingSize=37
;REMOVE AFTER UPDATE
SearchX=45
;The x value of the search bar in page 3
SearchY=15
;The y value of the search bar in page 3
DEVMODE=0,0,0,1
;Set 0,0,0,1 for off and 255,255,255,100 for on
Player=Spotify
;What is your music player?
MaxFreq=135
;Replace above value with your PC's maximum CPU frequency
SecondaryDrive=D
;Replace above value with your PC's secondary drive. Set it to null if there isn't one.
First=Wot
Second=Test out optimization by update=-1 and tweengroup
Third=Look for feedback possibly
Fourth=Fix text
Fifth=Task 5
Sixth=

;————————————————————————————————————————————————————————————————————————NOT CUSTOMIZABLE VALUES

Size=200
Step=1
ShapeWidth=495
PageChange=0
ShapeOffSet=2
PulseSize=0
PulseFill=255,0,0,100
SideYMod=0
LeftPairXMod=0
RightPairXMod=0
UpPairYMod=0
DownPairYMod=0
ShapeWidthX=0
SideOpacity=255
MiddleXMod=0
MiddleYMod=0
PowerCircleSize=0
AltPowerCircleSize=0
ButtonOffSet=0
ButtonOpacity=0
TextX=#TextDefaultX#
TextY=#TextDefaultY#
CircleFill=
CircleStroke=
PageTextContent=0
GameXScroll=0
MiddleRot=0
Editing=-1
TextBoxAlpha=0
;————————————————————————————————————————————————————————————————————————
