[ClipboardStyle]
FontSize=(12*(#BoxWidth#)/(#BoxWidth#))
StringAlign=Center
X=(#BoxWidth#*1.8/10)r
Y=r
W=(#BoxWidth#*2/10)
RightMouseUpAction=[!SetVariable ClipboardN #CURRENTSECTION#][!CommandMeasure ClipboardTextInput "ExecuteBatch ALL"]
Clipstring=2
FontColor=#Colormodeopposite#
Container=ClipboardContainer

[Clipboard1]
Meter=String
X=(#BoxWidth#*1.5/10)
Y=(#BoxWidth#*1/10)
Text=¡Ò
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ò][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard2]
Meter=String
Text=¡P
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡P][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard3]
Meter=String
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard4]
Meter=String
Text=?
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ?][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard5]
Meter=String
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard6]
Meter=String
X=(#BoxWidth#*1.5/10)
Y=(#BoxWidth#*1.8/10)r
Text=¡ï
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡ï][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard7]
Meter=String
Text=¡î
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡î][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard8]
Meter=String
Text=¢X
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¢X][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard9]
Meter=String
Text=$
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip $][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard10]
Meter=String
Text=£f
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip £f][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard11]
Meter=String
X=(#BoxWidth#*1.5/10)
Y=(#BoxWidth#*1.8/10)r
Text=£c
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip £c][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard12]
Meter=String
Text=¡u
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡u][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard13]
Meter=String
Text=¡v
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡v][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard14]
Meter=String
Text=¡C
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡C][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard15]
Meter=String
Text=¡÷
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡÷][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard16]
Meter=String
X=(#BoxWidth#*1.5/10)
Y=(#BoxWidth#*1.8/10)r
Text=¡¹
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡¹][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard17]
Meter=String
Text=¡µ
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡µ][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard18]
Meter=String
Text=¡Ú
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ú][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard19]
Meter=String
Text=¡ç
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡ç][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard20]
Meter=String
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard21]
Meter=String
X=(#BoxWidth#*1.5/10)
Y=(#BoxWidth#*1.8/10)r
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard22]
Meter=String
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard23]
Meter=String
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard24]
Meter=String
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[Clipboard25]
Meter=String
Text=¡Ô
MeterStyle=SemiBoldText | ClipboardStyle
LeftMouseUpAction=[!SetClip ¡Ô][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]

[ClipboardTextInput]
Measure=Plugin
Plugin=InputText
FontFace=SF Pro Display
AntiAlias=1
FontColor=150,150,150
FontSize=(7*(#BoxWidth#)/(#BoxWidth#))
StringAlign=Center
SolidColor=FFDB4C
W=(#BoxWidth#*8/10)
H=(#BoxWidth#*0.8/10)
X=([ClipboardBox:X]+(#BoxWidth#*1/10))
Y=([ClipboardBox:Y]+(#BoxWidth#*0.1/10))
DefaultValue=""
Command1=[!SetVariable LastClip """$UserInput$""" ""][!UpdateMeasure ClipboardContentUpdater]
FocusDismiss=1
DynamicVariables=1

[ClipboardContentUpdater]
Measure=Calc
Disabled=1
Group=NoUpdateOnLoad
DynamicVariables=1
OnUpdateAction=[!WriteKeyValue #ClipboardN# Text """#LastClip#""" "#@#Clipboard.inc"][!WriteKeyValue #ClipboardN# LeftMouseUpAction """[!SetClip #LastClip#][!ShowMeter ClipboardCopied][!Redraw][!Delay 500][!HideMeter ClipboardCopied][!Redraw]""" "#@#Clipboard.inc"][!SetOption #ClipboardN# Text """#LastClip#"""][!SetOption #ClipboardN# LeftMouseUpAction """!SetClip #LastClip#"""][!UpdateMeter #ClipboardN#][!Redraw]

[ClipboardCopied]
Meter=String
Text=Copied to clipboard
X=(#BoxWidth#/2)
Y=(#BoxWidth#*0.1/10)
FontFace=SF Pro Display
AntiAlias=1
FontColor=29,185,84
FontSize=(7*(#BoxWidth#)/(#BoxWidth#))
StringAlign=Center
Padding=5,0,5,0
Hidden=1
SolidColor=#ColorMode2#
Container=ClipboardContainer
