[mPath]
Measure=Plugin
Plugin=FileView
Path="#@#Applications\iPad"
DynamicVariables=1
COunt=28
UpdateDivider=1
ShowDotDot=0
ShowFolder=0

[mIndexFiles]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileCount
Group=Children 
OnChangeAction=[!UpdateMeterGroup TrayICons][!Redraw][!Delay 1000][!SetOption BottomBar UpdateDivider -1]
UpdateDivider=1

[mIndex1Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=1
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex2Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=2
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex3Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=3
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex4Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=4
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex5Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=5
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex6Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=6
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex7Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=7
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex8Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=8
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex9Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=9
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex10Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=10
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex11Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=11
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex12Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=12
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex13Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=13
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex14Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=14
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex15Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=15
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex16Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=16
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex17Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=17
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex18Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=18
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex19Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=19
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex20Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=20
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex21Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=21
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex22Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=22
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex23Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=23
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex24Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=24
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex25Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=25
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex26Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=26
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex27Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=27
Group=Children | Names
Substitute=".lnk":"",".url":""

[mIndex28Name]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=FileName
Index=28
Group=Children | Names
Substitute=".lnk":"",".url":""