[mPath]
Measure=Plugin
Plugin=FileView
Path="#@#Applications"
Count=27
ShowDotDot=0
ShowFolder=0

;[mIndex1Name]
;Measure=Plugin
;Plugin=FileView
;Path=[mPath]
;Type=FileName
;Index=1
;Group=Children

[mIndex1Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=1
Group=Children

[mIndex2Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=2
Group=Children

[mIndex3Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=3
Group=Children

[mIndex4Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=4
Group=Children

[mIndex5Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=5
Group=Children

[mIndex6Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=6
Group=Children

[mIndex7Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=7
Group=Children

[mIndex8Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=8
Group=Children

[mIndex9Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=9
Group=Children

[mIndex10Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=10
Group=Children

[mIndex11Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=11
Group=Children

[mIndex12Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=12
Group=Children

[mIndex13Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=13
Group=Children

[mIndex14Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=14
Group=Children

[mIndex15Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=15
Group=Children

[mIndex16Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=16
Group=Children

[mIndex17Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=17
Group=Children

[mIndex18Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=18
Group=Children

[mIndex19Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=19
Group=Children

[mIndex20Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=20
Group=Children

[mIndex21Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=21
Group=Children

[mIndex22Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=22
Group=Children

[mIndex23Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=23
Group=Children

[mIndex24Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=24
Group=Children

[mIndex25Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=25
Group=Children

[mIndex26Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=26
Group=Children

[mIndex27Icon]
Measure=Plugin
Plugin=FileView
Path=[mPath]
Type=Icon
IconSize=Medium
Index=27
Group=Children