;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[Variables]
;——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

lat=22.355181
long=114.103981
;Insert values for your location
APIKEY=988798ef1d25465aa6cba243738cf720
;Insert your Weather API key here
;————————————————————————————————————————————————————————————————————————
DashWidth=440
EventCalendarURL=https://calendar.google.com/calendar/ical/enhancedjax%40gmail.com/private-20479345f96787719c0d0011b57b5ea4/basic.ics
HolidayCalendarURL=https://www.1823.gov.hk/common/ical/en.ics
;Font=Segoe UI
Font=Oxanium
DashPicture=Basic.png
MainColor=4,4,4
SecondaryColor=30,30,30
FontColor=255,255,255
FontColor2=170,170,170
FontOppositeColor=10,10,10
AnimationSpeed=500
ImageOffSet=-80
Drive1=C
Drive2=D
Preload=0
Player=Spotify
Animations=0
ScreenSaver=1
ScreenSaverMode=AllTop
ScreenSaverInterval=300
;————————————————————————————————————————————————————————————————————————
Page=1
ElementX=583
LocationCode=8f0658124f5f5b725ca5ed254decc028fd2099a8ac1843faa2ceb206c9b464d1
URL=https://weather.com/#Language#/weather/today/l/#LocationCode#
Language=en-GB
TimeFormat=TimeFormat12H
;none or TimeFormat12H
SpeedUnit=Mph
VisibilityUnit=Km
;Km,Mile,Mb,In
FillColor=0,0,0,30
FillColor2=0,0,0,50
FontEffectColor=0,0,0,50
;————————————————————————————————————————————————————————————————————————
